### ISSUE TITLE
Share Message Always Returns 48

### ISSUE THREAD

**Issue by s4r4htonin** [jmausolf/poshmark_sharing#21]
This ran fine at first, but I am now having an issue where no matter how many available listings there are, the share message always returns 48 as the number of items in a closet. This issue is coming up with my own closet and when using -a to share items from a different closet. 

[*] sharing PoshMark listings for 48 items in closet...
    please wait...

I have tried setting -n to a different number, but that does not seem to make a difference. 

Does anyone have any suggestions about what is going on?

**Comment by jmausolf** [comment]
I actually encountered this issue when I tried to re-run the code on my laptop (but it was running fine on a different computer). It also showed `[*] sharing PoshMark listings for 48 items in closet...`

The issue seems to be a combination of updates to Poshmark's website no longer being compatible with older versions of Firefox. Once I updated Firefox, reinstalled geckodriver, and updated selenium, it worked as expected. So there's not an issue with the repository code, rather the packages, and programs it relies upon need updating on your system.
